name: set environment variables for gha-trigger
description: set environment variables for gha-trigger
inputs:
  data:
    description: gha-trigger's workflow dispatch input
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        # GITHUB_ACTOR
        # > The name of the person or app that initiated the workflow.
        # > For example, octocat.
        echo "GHA_ACTOR=${{inputs.data.event.sender.login}}" >> "$GITHUB_ENV"
        # GITHUB_EVENT_NAME
        echo "GHA_EVENT_NAME=${{inputs.data.event_name}}" >> "$GITHUB_ENV"
        # GITHUB_HEAD_REF
        echo "GHA_HEAD_REF=${{inputs.data.event.pull_request.head.ref}}" >> "$GITHUB_ENV"
        # GITHUB_POSITORY
        echo "GHA_REPOSITORY=${{inputs.data.event.repository.full_name}}" >> "$GITHUB_ENV"
        # GITHUB_POSITORY_OWNER
        echo "GHA_REPOSITORY_OWNER=${{inputs.data.event.repository.owner.login}}" >> "$GITHUB_ENV"
        # GITHUB_SHA
        echo "GHA_SHA=${{inputs.data.event.sha}}" >> "$GITHUB_ENV"
    - shell: bash
      # GITHUB_BASE_REF
      # > The name of the base ref or target branch of the pull request in a workflow run.
      # > This is only set when the event that triggers a workflow run is either pull_request or pull_request_target.
      # > For example, main.
      run: |
        echo "GHA_BASE_REF=${{inputs.data.event.pull_request.base.ref}}" >> "$GITHUB_ENV"
        echo "GHA_HEAD_SHA=${{inputs.data.event.pull_request.head.sha}}" >> "$GITHUB_ENV"
      if: inputs.data.event_name == 'pull_request' || inputs.data.event_name == 'pull_request_target'
    - shell: bash
      # GITHUB_REF
      # > For workflows triggered by pull_request, this is the pull request merge branch.
      run: |
        echo "GHA_REF=refs/pull/${{inputs.data.event.pull_request.number}}/merge" >> "$GITHUB_ENV"
        # GITHUB_REF_NAME
        echo "GHA_REF_NAME=${{inputs.data.event.pull_request.number}}/merge" >> "$GITHUB_ENV"
      if: inputs.data.event_name == 'pull_request'
    - shell: bash
      # GITHUB_REF
      # > For workflows triggered by release, this is the release tag created.
      run: |
        echo "GHA_REF=${{inputs.data.event.release.tag_name}}" >> "$GITHUB_ENV"
        # GITHUB_REF_NAME
        echo "GHA_REF_NAME=${{inputs.data.event.release.tag_name}}" >> "$GITHUB_ENV"
      if: inputs.data.event_name == 'release'
    - shell: bash
      # GITHUB_REF
      # > For workflows triggered by push, this is the branch or tag ref that was pushed.
      run: |
        echo "GHA_REF=${{inputs.data.event.ref}}" >> "$GITHUB_ENV"
        echo "GHA_REF_NAME=$(basename "${{inputs.data.event.ref}}")" >> "$GITHUB_ENV"
      if: inputs.data.event_name == 'push'
      # TODO GITHUB_REF
      # > The branch or tag ref that triggered the workflow run.
      # > For other triggers, this is the branch or tag ref that triggered the workflow run.
      # > This is only set if a branch or tag is available for the event type.
      # > The ref given is fully-formed, meaning that for branches the format is refs/heads/<branch_name>, for pull requests it is refs/pull/<pr_number>/merge, and for tags it is refs/tags/<tag_name>.
      # > For example, refs/heads/feature-branch-1.

      # TODO GITHUB_REF_NAME
      # > The branch or tag name that triggered the workflow run. For example, feature-branch-1.
