name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{env.DIRS}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.1"
          cache: true
      - run: go run ./cmd/list

  test:
    runs-on: ubuntu-latest
    name: "test (${{matrix.dir}})"
    needs: list-files
    env:
      DIR: ${{matrix.dir}}
    strategy:
      fail-fast: false
      matrix:
        dir: ${{fromJSON(needs.list-files.outputs.dirs)}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.1"
          cache: true
      - run: go run ./cmd/setter "$DIR"
      - uses: ./
        with:
          data: ${{env.DATA}}
      - run: go run ./cmd/tester "$DIR"
