name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{env.FILES}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.1"
          cache: true
      - run: go run ./cmd/list

  test:
    runs-on: ubuntu-latest
    name: "test (${{matrix.file}})"
    needs: list-files
    env:
      FILE: ${{matrix.file}}
    strategy:
      fail-fast: false
      matrix:
        file: ${{fromJSON(needs.list-files.outputs.files)}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.1"
          cache: true
      - run: go run ./cmd/setter "$FILE"
      - uses: ./
        with:
          data: ${{toJSON(fromJSON(env.DATA).data)}}
      - run: go run ./cmd/tester "$FILE"
