name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{env.FILES}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.1"
          cache: true
      - run: go run ./cmd/list

  test:
    runs-on: ubuntu-latest
    name: "test (${{matrix.file}})"
    needs: list-files
    env:
      FILE: ${{matrix.file}}
    strategy:
      fail-fast: false
      matrix:
        file: ${{fromJSON(needs.list-files.outputs.files)}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.1"
          cache: true
      - run: go run ./cmd/setter "$FILE"
      - uses: ./
        with:
          data: ${{toJSON(fromJSON(env.DATA).data)}}
      - run: go run ./cmd/tester "$FILE"

        #   test-push:
        #     runs-on: ubuntu-latest
        #     steps:
        #       - uses: actions/checkout@v3
        #       - uses: ./
        #         with:
        #           data: |
        #             {
        #               "event_name": "push",
        #               "event": {
        #                 "ref": "refs/heads/renovate/github.com-aws-aws-sdk-go-1.x",
        #                 "sender": {
        #                   "login": "suzuki-shunsuke"
        #                 },
        #                 "head_commit": {
        #                   "id": "a705bd6d8bc3882c983477cb3f20ab74ef8c24c2"
        #                 },
        #                 "repository": {
        #                   "full_name": "gha-trigger/gha-trigger",
        #                   "name": "gha-trigger",
        #                   "owner": {
        #                     "login": "gha-trigger"
        #                   }
        #                 }
        #               }
        #             }
        #   test-release:
        #     runs-on: ubuntu-latest
        #     steps:
        #       - uses: actions/checkout@v3
        #       - uses: ./
        #         with:
        #           data: |
        #             {
        #               "event_name": "release",
        #               "event": {
        #                 "sender": {
        #                   "login": "suzuki-shunsuke"
        #                 },
        #                 "release": {
        #                   "tag_name": "v0.1.0"
        #                 },
        #                 "repository": {
        #                   "full_name": "gha-trigger/gha-trigger",
        #                   "name": "gha-trigger",
        #                   "owner": {
        #                     "login": "gha-trigger"
        #                   }
        #                 }
        #               }
        #             }
        #       - name: Test GHA_ACTOR
        #         run: |
        #           [ "$GHA_ACTOR" = suzuki-shunsuke ]
        #       - name: Test GHA_EVENT_NAME
        #         run: |
        #           [ "$GHA_EVENT_NAME" = release ]
        #       - name: Test GHA_REPOSITORY
        #         run: |
        #           [ "$GHA_REPOSITORY" = gha-trigger/gha-trigger ]
        #       - name: Test GHA_REPOSITORY_OWNER
        #         run: |
        #           [ "$GHA_REPOSITORY_OWNER" = gha-trigger ]
        #       - name: Test GHA_REPOSITORY_NAME
        #         run: |
        #           [ "$GHA_REPOSITORY_NAME" = gha-trigger ]
        #       - name: Test GHA_SHA
        #         run: |
        #           [ "$GHA_SHA" = "" ]
        #       - name: Test GHA_REF
        #         run: |
        #           [ "$GHA_REF" = v0.1.0 ]
        #       - name: Test GHA_REF_NAME
        #         run: |
        #           [ "$GHA_REF_NAME" = v0.1.0 ]
        #       - name: Test GHA_ENV
        #         run: |
        #           [ -n "$GHA_ENV" ]
